name = "ExprRules"
uuid = "e7058ba0-a568-556c-b31a-209ee9d855a8"
authors = ["Ritchie Lee <ritchie@ritchielee.net>", "Mykel Kochenderfer <mykel@stanford.edu>"]
version = "0.4.1"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TreeView = "39424ebd-4cf3-5550-a685-96706a953f40"

[compat]
AbstractTrees = "0.2,0.3"
DataStructures = "0.17"
Nullables = "1.0"
StatsBase = "0.33"
TreeView = "0.3"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
